#krun -h k8s-master1 -c "kubectl  version --short"
#INFO 2021/01/08 17:31:39 【root@k8s-master1:22】 - CMD:kubectl  version --short - status:OK - result:
#Client Version: v1.16.0
#Server Version: v1.16.0
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: classes.school.lemon.io
spec:
  group: school.lemon.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                className: #班级名称
                  type: string
                techerName: #班主名称
                  type: string
                replicas:  #班级人数
                  type: integer
                  minimum: 1
                  maximum: 50
                status:
                  type: object
                  properties:
                    replicas:
                      type: integer
      additionalPrinterColumns:
        - name: 班级名称
          type: string
          description: 显示班级名称
          jsonPath: .spec.className
        - name: 班主任
          type: string
          description: 显示班主任
          jsonPath: .spec.techerName
        - name: 学生人数
          type: integer
          description: 显示班级学生人数
          jsonPath: .spec.replicas
        - name: 状态
          type: integer
          description: 显示班级状态
          jsonPath: .spec.replicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        #status 启用status子资源
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
  names:
    kind: Class
    plural: classes
    singular: class
    shortNames:
      - cl
      - ces
  scope: Namespaced

