#krun -h k8s-master1 -c "kubectl  version --short"
#INFO 2021/01/08 17:31:39 【root@k8s-master1:22】 - CMD:kubectl  version --short - status:OK - result:
#Client Version: v1.16.0
#Server Version: v1.16.0
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: classes.school.lemon.io
spec:
  group: school.lemon.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                className: #班级名称
                  type: string
                techerName: #班主名称
                  type: string
                replicas:  #班级人数
                  type: integer
                  minimum: 1
                  maximum: 50
            status:
              description: ApplicationStatus defines controller's the observed state of Application
              properties:
                components:
                  description: Object status array for all matching objects
                  items:
                    description: ObjectStatus is a generic status holder for objects
                    properties:
                      replicas:
                        description: 班级人数
                        type: integer
                      status:
                        description: 'Status. Values: InProgress, Ready, Unknown'
                        type: string
                    type: object
                  type: array
                componentsReady:
                  description: 'ComponentsReady: status of the components in the format ready/total'
                  type: string
                conditions:
                  description: Conditions represents the latest state of the object
                  items:
                    description: Condition describes the state of an object at a certain point.
                    properties:
                      lastTransitionTime:
                        description: Last time the condition transitioned from one status  to another.
                        format: date-time
                        type: string
                      lastUpdateTime:
                        description: Last time the condition was probed
                        format: date-time
                        type: string
                      message:
                        description: A human readable message indicating details about
                          the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of condition.
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                observedGeneration:
                  description: ObservedGeneration is the most recent generation observed.
                    It corresponds to the Object's generation, which is updated on mutation
                    by the API Server.
                  format: int64
                  type: integer
              type: object
      additionalPrinterColumns:
        - name: 班级名称
          type: string
          description: 显示班级名称
          jsonPath: .spec.className
        - name: 班主任
          type: string
          description: 显示班主任
          jsonPath: .spec.techerName
        - name: 学生人数
          type: integer
          description: 显示班级学生人数
          jsonPath: .spec.replicas
        - description: Numbers of components ready
          jsonPath: .status.componentsReady
          name: 状态
          type: string
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        #status 启用status子资源
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.labelSelector
  names:
    categories:
      - all
    kind: Class
    plural: classes
    singular: class
    shortNames:
      - cl
      - ces
  scope: Namespaced
status:
    acceptedNames:
      kind: ""
      plural: ""
    conditions: []
    storedVersions: []

