apiVersion: v1
kind: ServiceAccount
metadata:
  name: le-demo
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pods-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
      - "pods/log"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resources-reader
subjects:
  - kind: User
    name: kuber-user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader


---
# 设置集群参数
  kubectl config set-cluster kubernetes \
  --server=https://192.168.0.81:6443 \
  --certificate-authority=/opt/kubernetes/ssl/ca.pem \
  --embed-certs=true \
--kubeconfig=config

  # 设置上下文参数
kubectl config set-context kuber-user1 \
--cluster=kubernetes \
--user=kuber-user1 \
--kubeconfig=config

  # 设置客户端认证参数
kubectl config set-credentials kubernetes \
--certificate-authority=/opt/kubernetes/ssl/ca.pem \
--embed-certs=true \
--client-key=/opt/kubernetes/ssl/server-key.pem  \
--client-certificate=/opt/kubernetes/ssl/server.pem  \
--kubeconfig=config
---
kubectl config use-context kuber-user1@kubernetes --kubeconfig=config